/* The following code has been generated by `einit` program */

#include <stdlib.h>
#include <stdio.h>

#include <rtl/retcode.h>
#include <coresrv/entity/entity_api.h>
#include <services/handle/if_connection.h>



static const EndpointInfo endpointsInfo_drone_controller_AutopilotConnector_0[4] = {
    {
        .name = "drone_controller.AutopilotConnector.waitForInit",
        .riid = 0,
        .iface_name = "drone_controller.Initialization",
    },
    {
        .name = "waitForInit",
        .riid = 0,
        .iface_name = "drone_controller.Initialization",
    },
    {
        .name = "drone_controller.AutopilotConnector.interface",
        .riid = 1,
        .iface_name = "drone_controller.AutopilotConnectorInterface",
    },
    {
        .name = "interface",
        .riid = 1,
        .iface_name = "drone_controller.AutopilotConnectorInterface",
    }
};
static const EntityInfo taskInfo_drone_controller_AutopilotConnector_0 = {
    .eiid = "drone_controller.AutopilotConnector",
    .max_endpoints = 4,
    .endpoints = endpointsInfo_drone_controller_AutopilotConnector_0,
};
static const EndpointInfo endpointsInfo_drone_controller_CredentialManager_1[4] = {
    {
        .name = "drone_controller.CredentialManager.waitForInit",
        .riid = 0,
        .iface_name = "drone_controller.Initialization",
    },
    {
        .name = "waitForInit",
        .riid = 0,
        .iface_name = "drone_controller.Initialization",
    },
    {
        .name = "drone_controller.CredentialManager.interface",
        .riid = 1,
        .iface_name = "drone_controller.CredentialManagerInterface",
    },
    {
        .name = "interface",
        .riid = 1,
        .iface_name = "drone_controller.CredentialManagerInterface",
    }
};
static const EntityInfo taskInfo_drone_controller_CredentialManager_1 = {
    .eiid = "drone_controller.CredentialManager",
    .max_endpoints = 4,
    .endpoints = endpointsInfo_drone_controller_CredentialManager_1,
};
static const EntityInfo taskInfo_drone_controller_FlightController_2 = {
    .eiid = "drone_controller.FlightController",
    .max_endpoints = 0,
    .endpoints = NK_NULL,
};
static const EndpointInfo endpointsInfo_drone_controller_NavigationSystem_3[4] = {
    {
        .name = "drone_controller.NavigationSystem.waitForInit",
        .riid = 0,
        .iface_name = "drone_controller.Initialization",
    },
    {
        .name = "waitForInit",
        .riid = 0,
        .iface_name = "drone_controller.Initialization",
    },
    {
        .name = "drone_controller.NavigationSystem.interface",
        .riid = 1,
        .iface_name = "drone_controller.NavigationSystemInterface",
    },
    {
        .name = "interface",
        .riid = 1,
        .iface_name = "drone_controller.NavigationSystemInterface",
    }
};
static const EntityInfo taskInfo_drone_controller_NavigationSystem_3 = {
    .eiid = "drone_controller.NavigationSystem",
    .max_endpoints = 4,
    .endpoints = endpointsInfo_drone_controller_NavigationSystem_3,
};
static const EndpointInfo endpointsInfo_drone_controller_PeripheryController_4[4] = {
    {
        .name = "drone_controller.PeripheryController.waitForInit",
        .riid = 0,
        .iface_name = "drone_controller.Initialization",
    },
    {
        .name = "waitForInit",
        .riid = 0,
        .iface_name = "drone_controller.Initialization",
    },
    {
        .name = "drone_controller.PeripheryController.interface",
        .riid = 1,
        .iface_name = "drone_controller.PeripheryControllerInterface",
    },
    {
        .name = "interface",
        .riid = 1,
        .iface_name = "drone_controller.PeripheryControllerInterface",
    }
};
static const EntityInfo taskInfo_drone_controller_PeripheryController_4 = {
    .eiid = "drone_controller.PeripheryController",
    .max_endpoints = 4,
    .endpoints = endpointsInfo_drone_controller_PeripheryController_4,
};
static const EndpointInfo endpointsInfo_drone_controller_ServerConnector_5[4] = {
    {
        .name = "drone_controller.ServerConnector.waitForInit",
        .riid = 0,
        .iface_name = "drone_controller.Initialization",
    },
    {
        .name = "waitForInit",
        .riid = 0,
        .iface_name = "drone_controller.Initialization",
    },
    {
        .name = "drone_controller.ServerConnector.interface",
        .riid = 1,
        .iface_name = "drone_controller.ServerConnectorInterface",
    },
    {
        .name = "interface",
        .riid = 1,
        .iface_name = "drone_controller.ServerConnectorInterface",
    }
};
static const EntityInfo taskInfo_drone_controller_ServerConnector_5 = {
    .eiid = "drone_controller.ServerConnector",
    .max_endpoints = 4,
    .endpoints = endpointsInfo_drone_controller_ServerConnector_5,
};
static const EndpointInfo endpointsInfo_kl_EntropyEntity_6[2] = {
    {
        .name = "kl.Entropy.entropy",
        .riid = 0,
        .iface_name = "kl.Entropy",
    },
    {
        .name = "entropy.entropy",
        .riid = 0,
        .iface_name = "kl.Entropy",
    }
};
static const EntityInfo taskInfo_kl_EntropyEntity_6 = {
    .eiid = "kl.EntropyEntity",
    .max_endpoints = 2,
    .endpoints = endpointsInfo_kl_EntropyEntity_6,
};
static const EndpointInfo endpointsInfo_kl_VfsNet_7[14] = {
    {
        .name = "kl.Vfs.server",
        .riid = 0,
        .iface_name = "kl.VfsFilesystem",
    },
    {
        .name = "vfs.server",
        .riid = 0,
        .iface_name = "kl.VfsFilesystem",
    },
    {
        .name = "kl.Vfs.netcfg",
        .riid = 1,
        .iface_name = "kl.VfsNetConfig",
    },
    {
        .name = "vfs.netcfg",
        .riid = 1,
        .iface_name = "kl.VfsNetConfig",
    },
    {
        .name = "kl.Vfs.bpfcfg",
        .riid = 2,
        .iface_name = "kl.VfsBPFilter",
    },
    {
        .name = "vfs.bpfcfg",
        .riid = 2,
        .iface_name = "kl.VfsBPFilter",
    },
    {
        .name = "kl.Vfs.npfcfg",
        .riid = 3,
        .iface_name = "kl.VfsNPFilter",
    },
    {
        .name = "vfs.npfcfg",
        .riid = 3,
        .iface_name = "kl.VfsNPFilter",
    },
    {
        .name = "kl.Vfs.xattrcfg",
        .riid = 4,
        .iface_name = "kl.VfsExtAttr",
    },
    {
        .name = "vfs.xattrcfg",
        .riid = 4,
        .iface_name = "kl.VfsExtAttr",
    },
    {
        .name = "kl.Vfs.aclcfg",
        .riid = 5,
        .iface_name = "kl.VfsACL",
    },
    {
        .name = "vfs.aclcfg",
        .riid = 5,
        .iface_name = "kl.VfsACL",
    },
    {
        .name = "kl.Vfs.native",
        .riid = 6,
        .iface_name = "kl.VfsNative",
    },
    {
        .name = "vfs.native",
        .riid = 6,
        .iface_name = "kl.VfsNative",
    }
};
static const EntityInfo taskInfo_kl_VfsNet_7 = {
    .eiid = "kl.VfsNet",
    .max_endpoints = 14,
    .endpoints = endpointsInfo_kl_VfsNet_7,
};
static const EndpointInfo endpointsInfo_kl_drivers_Bcm2711MboxArmToVc_8[4] = {
    {
        .name = "kl.drivers.Bcm2711MboxArmToVc.driver",
        .riid = 0,
        .iface_name = "kl.drivers.Driver",
    },
    {
        .name = "driver",
        .riid = 0,
        .iface_name = "kl.drivers.Driver",
    },
    {
        .name = "kl.drivers.Bcm2711MboxArmToVc.bcm2711mboxarmtovc",
        .riid = 1,
        .iface_name = "kl.drivers.Bcm2711MboxArmToVc",
    },
    {
        .name = "bcm2711mboxarmtovc",
        .riid = 1,
        .iface_name = "kl.drivers.Bcm2711MboxArmToVc",
    }
};
static const EntityInfo taskInfo_kl_drivers_Bcm2711MboxArmToVc_8 = {
    .eiid = "kl.drivers.Bcm2711MboxArmToVc",
    .max_endpoints = 4,
    .endpoints = endpointsInfo_kl_drivers_Bcm2711MboxArmToVc_8,
};
static const EndpointInfo endpointsInfo_kl_drivers_DNetSrv_9[8] = {
    {
        .name = "kl.drivers.DNet.dnet",
        .riid = 0,
        .iface_name = "kl.drivers.DNet",
    },
    {
        .name = "dnet.dnet",
        .riid = 0,
        .iface_name = "kl.drivers.DNet",
    },
    {
        .name = "kl.drivers.DNet.mac",
        .riid = 1,
        .iface_name = "kl.drivers.DNetMac",
    },
    {
        .name = "dnet.mac",
        .riid = 1,
        .iface_name = "kl.drivers.DNetMac",
    },
    {
        .name = "kl.drivers.DNet.wifi",
        .riid = 2,
        .iface_name = "kl.drivers.DNetWifi",
    },
    {
        .name = "dnet.wifi",
        .riid = 2,
        .iface_name = "kl.drivers.DNetWifi",
    },
    {
        .name = "kl.drivers.DNet.supplicant",
        .riid = 3,
        .iface_name = "kl.drivers.DNetSupplicant",
    },
    {
        .name = "dnet.supplicant",
        .riid = 3,
        .iface_name = "kl.drivers.DNetSupplicant",
    }
};
static const EntityInfo taskInfo_kl_drivers_DNetSrv_9 = {
    .eiid = "kl.drivers.DNetSrv",
    .max_endpoints = 8,
    .endpoints = endpointsInfo_kl_drivers_DNetSrv_9,
};
static const EndpointInfo endpointsInfo_kl_rump_Dhcpcd_10[2] = {
    {
        .name = "kl.rump.Dhcpcd.dhcpcd",
        .riid = 0,
        .iface_name = "kl.rump.DhcpcdConfig",
    },
    {
        .name = "dhcpcd",
        .riid = 0,
        .iface_name = "kl.rump.DhcpcdConfig",
    }
};
static const EntityInfo taskInfo_kl_rump_Dhcpcd_10 = {
    .eiid = "kl.rump.Dhcpcd",
    .max_endpoints = 2,
    .endpoints = endpointsInfo_kl_rump_Dhcpcd_10,
};

/* init entity entry point */
int main(void) {

    Entity * task_drone_controller_AutopilotConnector_0;
    Entity * task_drone_controller_CredentialManager_1;
    Entity * task_drone_controller_FlightController_2;
    Entity * task_drone_controller_NavigationSystem_3;
    Entity * task_drone_controller_PeripheryController_4;
    Entity * task_drone_controller_ServerConnector_5;
    Entity * task_kl_EntropyEntity_6;
    Entity * task_kl_VfsNet_7;
    Entity * task_kl_drivers_Bcm2711MboxArmToVc_8;
    Entity * task_kl_drivers_DNetSrv_9;
    Entity * task_kl_rump_Dhcpcd_10;
    const char * taskInfo_drone_controller_AutopilotConnector_0_env[] = {
        "VFS_FILESYSTEM_BACKEND=client:kl.VfsNet",
        "VFS_NETWORK_BACKEND=client:kl.VfsNet",
        RTL_NULL
    };
    const char * taskInfo_drone_controller_CredentialManager_1_env[] = {
        "VFS_FILESYSTEM_BACKEND=client:kl.VfsNet",
        RTL_NULL
    };

    const char * taskInfo_drone_controller_NavigationSystem_3_env[] = {
        "VFS_FILESYSTEM_BACKEND=client:kl.VfsNet",
        "VFS_NETWORK_BACKEND=client:kl.VfsNet",
        RTL_NULL
    };
    const char * taskInfo_drone_controller_PeripheryController_4_env[] = {
        "VFS_FILESYSTEM_BACKEND=client:kl.VfsNet",
        "VFS_NETWORK_BACKEND=client:kl.VfsNet",
        RTL_NULL
    };


    const char * taskInfo_kl_VfsNet_7_env[] = {
        "DEFAULT_DNS_SERVER=8.8.8.8",
        "VFS_FILESYSTEM_BACKEND=server:kl.VfsNet",
        "VFS_NETWORK_BACKEND=server:kl.VfsNet",
        RTL_NULL
    };


    const char * taskInfo_kl_rump_Dhcpcd_10_env[] = {
        "VFS_FILESYSTEM_BACKEND=client:kl.VfsNet",
        "VFS_NETWORK_BACKEND=client:kl.VfsNet",
        RTL_NULL
    };
    const char * taskInfo_drone_controller_AutopilotConnector_0_args[] = {
        "AutopilotConnector",
        "-sV4",
        RTL_NULL
    };
    const char * taskInfo_drone_controller_CredentialManager_1_args[] = {
        "CredentialManager",
        RTL_NULL
    };
    const char * taskInfo_drone_controller_FlightController_2_args[] = {
        "FlightController",
        RTL_NULL
    };
    const char * taskInfo_drone_controller_NavigationSystem_3_args[] = {
        "NavigationSystem",
        "-sV4",
        RTL_NULL
    };
    const char * taskInfo_drone_controller_PeripheryController_4_args[] = {
        "PeripheryController",
        "-sV4",
        RTL_NULL
    };
    const char * taskInfo_drone_controller_ServerConnector_5_args[] = {
        "ServerConnector",
        RTL_NULL
    };
    const char * taskInfo_kl_EntropyEntity_6_args[] = {
        "Entropy",
        RTL_NULL
    };
    const char * taskInfo_kl_VfsNet_7_args[] = {
        "VfsNet",
        "-l",
        "devfs /dev devfs rw",
        "-l",
        "ramfs /tmp ramfs rw",
        "-l",
        "romfs /etc romfs ro",
        RTL_NULL
    };
    const char * taskInfo_kl_drivers_Bcm2711MboxArmToVc_8_args[] = {
        "bcm2711_mbox_arm2vc_qemu",
        RTL_NULL
    };
    const char * taskInfo_kl_drivers_DNetSrv_9_args[] = {
        "dnet_entity",
        RTL_NULL
    };
    const char * taskInfo_kl_rump_Dhcpcd_10_args[] = {
        "dhcpcd_entity",
        "-4",
        "-f",
        "/etc/dhcpcd.conf",
        RTL_NULL
    };

    /* initialize entities */

    task_kl_drivers_Bcm2711MboxArmToVc_8 = EntityInitEx(
        &taskInfo_kl_drivers_Bcm2711MboxArmToVc_8, "kl.drivers.Bcm2711MboxArmToVc", "bcm2711_mbox_arm2vc_qemu"
    );
    if (!task_kl_drivers_Bcm2711MboxArmToVc_8) {
        fprintf(
            stderr, "Can't initialize task \"kl.drivers.Bcm2711MboxArmToVc\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_kl_drivers_Bcm2711MboxArmToVc_8, taskInfo_kl_drivers_Bcm2711MboxArmToVc_8_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.drivers.Bcm2711MboxArmToVc\"\n"
        );
        return EXIT_FAILURE;
    }
    task_kl_drivers_DNetSrv_9 = EntityInitEx(
        &taskInfo_kl_drivers_DNetSrv_9, "kl.drivers.DNetSrv", "dnet_entity"
    );
    if (!task_kl_drivers_DNetSrv_9) {
        fprintf(
            stderr, "Can't initialize task \"kl.drivers.DNetSrv\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_kl_drivers_DNetSrv_9, taskInfo_kl_drivers_DNetSrv_9_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.drivers.DNetSrv\"\n"
        );
        return EXIT_FAILURE;
    }
    task_kl_EntropyEntity_6 = EntityInitEx(
        &taskInfo_kl_EntropyEntity_6, "kl.EntropyEntity", "Entropy"
    );
    if (!task_kl_EntropyEntity_6) {
        fprintf(
            stderr, "Can't initialize task \"kl.EntropyEntity\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_kl_EntropyEntity_6, taskInfo_kl_EntropyEntity_6_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.EntropyEntity\"\n"
        );
        return EXIT_FAILURE;
    }
    task_kl_VfsNet_7 = EntityInitEx(
        &taskInfo_kl_VfsNet_7, "kl.VfsNet", "VfsNet"
    );
    if (!task_kl_VfsNet_7) {
        fprintf(
            stderr, "Can't initialize task \"kl.VfsNet\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetEnv(task_kl_VfsNet_7, taskInfo_kl_VfsNet_7_env) != rcOk) {
        fprintf(
            stderr, "Can't set env for task \"kl.VfsNet\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetArgs(task_kl_VfsNet_7, taskInfo_kl_VfsNet_7_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.VfsNet\"\n"
        );
        return EXIT_FAILURE;
    }
    task_kl_rump_Dhcpcd_10 = EntityInitEx(
        &taskInfo_kl_rump_Dhcpcd_10, "kl.rump.Dhcpcd", "dhcpcd_entity"
    );
    if (!task_kl_rump_Dhcpcd_10) {
        fprintf(
            stderr, "Can't initialize task \"kl.rump.Dhcpcd\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetEnv(task_kl_rump_Dhcpcd_10, taskInfo_kl_rump_Dhcpcd_10_env) != rcOk) {
        fprintf(
            stderr, "Can't set env for task \"kl.rump.Dhcpcd\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetArgs(task_kl_rump_Dhcpcd_10, taskInfo_kl_rump_Dhcpcd_10_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"kl.rump.Dhcpcd\"\n"
        );
        return EXIT_FAILURE;
    }
    task_drone_controller_ServerConnector_5 = EntityInitEx(
        &taskInfo_drone_controller_ServerConnector_5, "drone_controller.ServerConnector", "ServerConnector"
    );
    if (!task_drone_controller_ServerConnector_5) {
        fprintf(
            stderr, "Can't initialize task \"drone_controller.ServerConnector\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_drone_controller_ServerConnector_5, taskInfo_drone_controller_ServerConnector_5_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"drone_controller.ServerConnector\"\n"
        );
        return EXIT_FAILURE;
    }
    task_drone_controller_CredentialManager_1 = EntityInitEx(
        &taskInfo_drone_controller_CredentialManager_1, "drone_controller.CredentialManager", "CredentialManager"
    );
    if (!task_drone_controller_CredentialManager_1) {
        fprintf(
            stderr, "Can't initialize task \"drone_controller.CredentialManager\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetEnv(task_drone_controller_CredentialManager_1, taskInfo_drone_controller_CredentialManager_1_env) != rcOk) {
        fprintf(
            stderr, "Can't set env for task \"drone_controller.CredentialManager\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetArgs(task_drone_controller_CredentialManager_1, taskInfo_drone_controller_CredentialManager_1_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"drone_controller.CredentialManager\"\n"
        );
        return EXIT_FAILURE;
    }
    task_drone_controller_NavigationSystem_3 = EntityInitEx(
        &taskInfo_drone_controller_NavigationSystem_3, "drone_controller.NavigationSystem", "NavigationSystem"
    );
    if (!task_drone_controller_NavigationSystem_3) {
        fprintf(
            stderr, "Can't initialize task \"drone_controller.NavigationSystem\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetEnv(task_drone_controller_NavigationSystem_3, taskInfo_drone_controller_NavigationSystem_3_env) != rcOk) {
        fprintf(
            stderr, "Can't set env for task \"drone_controller.NavigationSystem\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetArgs(task_drone_controller_NavigationSystem_3, taskInfo_drone_controller_NavigationSystem_3_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"drone_controller.NavigationSystem\"\n"
        );
        return EXIT_FAILURE;
    }
    task_drone_controller_PeripheryController_4 = EntityInitEx(
        &taskInfo_drone_controller_PeripheryController_4, "drone_controller.PeripheryController", "PeripheryController"
    );
    if (!task_drone_controller_PeripheryController_4) {
        fprintf(
            stderr, "Can't initialize task \"drone_controller.PeripheryController\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetEnv(task_drone_controller_PeripheryController_4, taskInfo_drone_controller_PeripheryController_4_env) != rcOk) {
        fprintf(
            stderr, "Can't set env for task \"drone_controller.PeripheryController\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetArgs(task_drone_controller_PeripheryController_4, taskInfo_drone_controller_PeripheryController_4_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"drone_controller.PeripheryController\"\n"
        );
        return EXIT_FAILURE;
    }
    task_drone_controller_AutopilotConnector_0 = EntityInitEx(
        &taskInfo_drone_controller_AutopilotConnector_0, "drone_controller.AutopilotConnector", "AutopilotConnector"
    );
    if (!task_drone_controller_AutopilotConnector_0) {
        fprintf(
            stderr, "Can't initialize task \"drone_controller.AutopilotConnector\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetEnv(task_drone_controller_AutopilotConnector_0, taskInfo_drone_controller_AutopilotConnector_0_env) != rcOk) {
        fprintf(
            stderr, "Can't set env for task \"drone_controller.AutopilotConnector\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntitySetArgs(task_drone_controller_AutopilotConnector_0, taskInfo_drone_controller_AutopilotConnector_0_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"drone_controller.AutopilotConnector\"\n"
        );
        return EXIT_FAILURE;
    }
    task_drone_controller_FlightController_2 = EntityInitEx(
        &taskInfo_drone_controller_FlightController_2, "drone_controller.FlightController", "FlightController"
    );
    if (!task_drone_controller_FlightController_2) {
        fprintf(
            stderr, "Can't initialize task \"drone_controller.FlightController\"\n"
        );
        return EXIT_FAILURE;
    }

    if (EntitySetArgs(task_drone_controller_FlightController_2, taskInfo_drone_controller_FlightController_2_args) != rcOk) {
        fprintf(
            stderr, "Can't set args for task \"drone_controller.FlightController\"\n"
        );
        return EXIT_FAILURE;
    }

    /* setup connections between entities */

    if (EntityConnectToService(task_kl_drivers_DNetSrv_9, task_kl_drivers_Bcm2711MboxArmToVc_8, "kl.drivers.Bcm2711MboxArmToVc") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.drivers.Bcm2711MboxArmToVc");
        return EXIT_FAILURE;
    }

    if (EntityConnectToService(task_kl_VfsNet_7, task_kl_EntropyEntity_6, "kl.EntropyEntity") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.EntropyEntity");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_kl_VfsNet_7, task_kl_drivers_DNetSrv_9, "kl.drivers.DNet") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.drivers.DNet");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_kl_rump_Dhcpcd_10, task_kl_VfsNet_7, "kl.VfsNet") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.VfsNet");
        return EXIT_FAILURE;
    }

    if (EntityConnectToService(task_drone_controller_CredentialManager_1, task_kl_VfsNet_7, "kl.VfsNet") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.VfsNet");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_CredentialManager_1, task_drone_controller_ServerConnector_5, "server_connector_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "server_connector_connection");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_NavigationSystem_3, task_drone_controller_CredentialManager_1, "credential_manager_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "credential_manager_connection");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_NavigationSystem_3, task_kl_VfsNet_7, "kl.VfsNet") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.VfsNet");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_NavigationSystem_3, task_drone_controller_ServerConnector_5, "server_connector_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "server_connector_connection");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_PeripheryController_4, task_drone_controller_CredentialManager_1, "credential_manager_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "credential_manager_connection");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_PeripheryController_4, task_kl_VfsNet_7, "kl.VfsNet") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.VfsNet");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_PeripheryController_4, task_drone_controller_ServerConnector_5, "server_connector_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "server_connector_connection");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_AutopilotConnector_0, task_kl_VfsNet_7, "kl.VfsNet") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "kl.VfsNet");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_FlightController_2, task_drone_controller_AutopilotConnector_0, "autopilot_connector_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "autopilot_connector_connection");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_FlightController_2, task_drone_controller_CredentialManager_1, "credential_manager_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "credential_manager_connection");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_FlightController_2, task_drone_controller_NavigationSystem_3, "navigation_system_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "navigation_system_connection");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_FlightController_2, task_drone_controller_PeripheryController_4, "periphery_controller_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "periphery_controller_connection");
        return EXIT_FAILURE;
    }
    if (EntityConnectToService(task_drone_controller_FlightController_2, task_drone_controller_ServerConnector_5, "server_connector_connection") != rcOk) {
        fprintf(stderr, "Can't setup a connection %s\n", "server_connector_connection");
        return EXIT_FAILURE;
    }



    /* run entities */

    if (EntityRun(task_kl_drivers_Bcm2711MboxArmToVc_8) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.drivers.Bcm2711MboxArmToVc\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_kl_drivers_DNetSrv_9) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.drivers.DNetSrv\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_kl_EntropyEntity_6) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.EntropyEntity\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_kl_VfsNet_7) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.VfsNet\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_kl_rump_Dhcpcd_10) != rcOk) {
        fprintf(
            stderr, "Can't run task \"kl.rump.Dhcpcd\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_drone_controller_ServerConnector_5) != rcOk) {
        fprintf(
            stderr, "Can't run task \"drone_controller.ServerConnector\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_drone_controller_CredentialManager_1) != rcOk) {
        fprintf(
            stderr, "Can't run task \"drone_controller.CredentialManager\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_drone_controller_NavigationSystem_3) != rcOk) {
        fprintf(
            stderr, "Can't run task \"drone_controller.NavigationSystem\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_drone_controller_PeripheryController_4) != rcOk) {
        fprintf(
            stderr, "Can't run task \"drone_controller.PeripheryController\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_drone_controller_AutopilotConnector_0) != rcOk) {
        fprintf(
            stderr, "Can't run task \"drone_controller.AutopilotConnector\"\n"
        );
        return EXIT_FAILURE;
    }
    if (EntityRun(task_drone_controller_FlightController_2) != rcOk) {
        fprintf(
            stderr, "Can't run task \"drone_controller.FlightController\"\n"
        );
        return EXIT_FAILURE;
    }





    return EXIT_SUCCESS;
}
